/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SrBirkhoff;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author doritos
 */
public class jogos extends javax.swing.JFrame {

    /**
     * Creates new form jogos
     */
    public jogos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        minecraftb = new javax.swing.JButton();
        gtab = new javax.swing.JButton();
        paydayb = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ProjectZ - Games");
        setExtendedState(6);

        jPanel1.setBackground(new java.awt.Color(19, 19, 19));
        jPanel1.setForeground(new java.awt.Color(254, 254, 254));
        jPanel1.setPreferredSize(new java.awt.Dimension(1198, 554));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/voltar.png"))); // NOI18N
        jLabel2.setToolTipText("Voltar Ao Menu Principal");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/mais.png"))); // NOI18N
        jLabel1.setToolTipText("Mais Jogos Em Breve! :)");

        minecraftb.setBackground(new java.awt.Color(86, 28, 4));
        minecraftb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/minecraft.png"))); // NOI18N
        minecraftb.setToolTipText("Minecraft");
        minecraftb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minecraftbActionPerformed(evt);
            }
        });

        gtab.setBackground(new java.awt.Color(1, 66, 19));
        gtab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/gta.png"))); // NOI18N
        gtab.setToolTipText("GTA - San Andreas");
        gtab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gtabActionPerformed(evt);
            }
        });

        paydayb.setBackground(new java.awt.Color(1, 65, 180));
        paydayb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/payday.png"))); // NOI18N
        paydayb.setToolTipText("PayDay - The Heist");
        paydayb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paydaybActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(minecraftb)
                .addGap(52, 52, 52)
                .addComponent(gtab)
                .addGap(52, 52, 52)
                .addComponent(paydayb)
                .addGap(52, 52, 52)
                .addComponent(jLabel1)
                .addContainerGap(448, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(paydayb)
                    .addComponent(gtab)
                    .addComponent(minecraftb))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 339, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1180, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 601, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        new MainProjectZ().setVisible(true);
        this.setVisible (false);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void minecraftbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minecraftbActionPerformed
        // minecraft
        String comando = "java -jar /home/doritos/ProjectZ/Minecraft.jar";  // diretório do programa a ser executado a baixo
        try {  
            Process processo = Runtime.getRuntime().exec(comando); // executa o programa minecraft :)
        } catch (IOException ex) {
            Logger.getLogger(jogos.class.getName()).log(Level.SEVERE, null, ex);
        }
                  setExtendedState(ICONIFIED); // minimiza a janela
    }//GEN-LAST:event_minecraftbActionPerformed

    private void gtabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gtabActionPerformed
        // gta
        String comando = "sh /home/doritos/ProjectZ/gta.sh"; 
        try {  
            Process processo = Runtime.getRuntime().exec(comando); // executa o programa Grand Theft Auto - San Andreas
        } catch (IOException ex) {
            Logger.getLogger(jogos.class.getName()).log(Level.SEVERE, null, ex);
        }
                  setExtendedState(ICONIFIED); // minimiza a janela
    }//GEN-LAST:event_gtabActionPerformed

    private void paydaybActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paydaybActionPerformed
        // payday
        String comando = "wine /home/doritos/Programas/payday/payday_win32_release.exe"; 
        try {  
            Process processo = Runtime.getRuntime().exec(comando); // executa o programa payday
        } catch (IOException ex) {
            Logger.getLogger(jogos.class.getName()).log(Level.SEVERE, null, ex);
        }
                  setExtendedState(ICONIFIED); // minimiza a janela
    }//GEN-LAST:event_paydaybActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jogos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jogos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jogos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jogos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jogos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton gtab;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton minecraftb;
    private javax.swing.JButton paydayb;
    // End of variables declaration//GEN-END:variables
}
